### ISSUE TITLE
cancel unsubmitted datapoints

### ISSUE THREAD

**Issue by bsoule** [beeminder/beedroid-issues#40]
From a user:

"On the Android app, it'd be useful to be able to edit a datapoint before it's sent."

-- or at least cancel it, perhaps?

<img width="236" alt="android_app_feedback_-_beemsup_gmail_com_-_gmail" src="https://user-images.githubusercontent.com/46881/38449784-e83de8dc-39c8-11e8-8924-ee464f9d238f.png">

**Comment by dreeves** [comment]
Sounds super cornercasey to me! Maybe we should hear more about the use case? But even with a reasonable sounding use case I'd be pretty skeptical that it would be worth the dev effort and the small increase in cognitive complexity of the UI in order to implement it.

I mean, almost all the time, the datapoint will be red for like a second or something and then it will have gone through and you can proceed to edit it or delete it as you like.
