### ISSUE TITLE
Clear "panic" notifications automatically when the graph updates and I'm no longer in panic mode

### ISSUE THREAD

**Issue by adamwolf** [beeminder/beedroid-issues#56]

**Comment by saranli** [comment]
This was normally a feature that I had implemented and tested back in the day, but API changes along the way must have broken it somehow.

**Comment by adamwolf** [comment]
This works, but not how I would expect.  When a zeno would update, it checks to see if it should remove itself.  When goals get data, I would expect they would see if they have a zeno and clear them.  Thoughts? cc @dreeves

**Comment by dreeves** [comment]
No strong opinions on this. (The way the zenos are working now in the beta works for me personally. I'm probably inclined to have them err on the side of not magically disappearing because swiping them away is so easy. But minimizing wolf-crying seems an equally worthy goal!) I think everything I just said in parens cancels itself out...

**Comment by adamwolf** [comment]
This is not how notifications work across other parts of Beeminder, so we're going to close this.
