### ISSUE TITLE
Ruthlessly purge settings: Zeno enabled and Zeno Start et al in Goal settings

### ISSUE THREAD

**Issue by dreeves** [beeminder/beedroid-issues#62]
![image](https://user-images.githubusercontent.com/9928/55577905-861d6780-56c9-11e9-91f8-17f71d5b58f6.png)

## Notification settings

1. panic buffer (number of days)
2. zeno start time
3. zeno checkbox

It's decided that we're killing panic buffer. Zeno checkbox and start time stay, until later when we use beeminder.com/reminders on the website for setting all reminders including Beedroid.

## Title

This dies because it's settable on the website (not to mention the turmoil with slugs/goalnames/blurbs/descriptions/titles/fineprint/ids that we're still sorting out).

## Keep it secret. Keep it safe.

Dies (settable on website).

## Make datapoints public.

Dies (settable on website).

**Comment by dreeves** [comment]
Update: we can kill Goal Settings completely since we have the fwomp page of zeno start time and zeno checkboxes for each goal in general settings under "Emergency day notifications"!

**Comment by adamwolf** [comment]
Panic buffer days is used in the app as the number of days before deadline to show Zeno reminders.  This should pull from leadtime for the goal on the website, right @dreeves?

**Comment by adamwolf** [comment]
Can we not mark this Mendoza for the next release?  I'm skeptical we can do this change and get it working well before our May 28th deadline, because of something I just realized.

We actually don't have a built-in way right now for notifying in a non-zeno way.  i.e. if you have lead-days set to 7, you're going to be on the zeno schedule for all of those 7 days, rather than "once daily until emergency, then zeno".

I do not think this is a big change, and if it was the only thing on the list for this week I think it would be fine, but combined with the other things, I'd rather leave it like this until the next release.  There's also a chance that we'll get some emergency user feedback from this release and I want to reserve some time for that too.

**Comment by dreeves** [comment]
Agreed. I don't know why I mendoza'd it in the first place. We should only mendoza things we have to (tentatively including all regressions per the [pareto dominance principle](http://doc.bmndr.com/pdp) but we can debate those)!

**Comment by adamwolf** [comment]
This was done in f2d8711d792d6674236329d1576e2839139c2ce2, which is already in the 3.3.x betas, but not yet released to the public.

**Comment by adamwolf** [comment]
This has been released.
