### ISSUE TITLE
Review signups in app

### ISSUE THREAD

**Issue by adamwolf** [beeminder/beedroid-issues#68]
1) what’s the state of error messaging when you try to sign up for a new account via beedroid?
2) what does the app do on success?

there was a user having trouble signing up for an account yesterday.

**Comment by bsoule** [comment]
i just tried this out. 

the error messaging is easy to miss because it just blends right into the interface. also it says "username is taken" when i give a username with bad characters in it. It'd be friendlier to point out the restriction on special characters.

after successfully creating an account the app did sensible things, like bring me to the main app page and giving me a big "start a new goal" button. etc.

**Comment by bsoule** [comment]
So in conclusion: 
* make error messages more specific in beedroid
* make error messages more noticable

**Comment by adamwolf** [comment]
We point folks to the website now for signups, so this isn't an issue.
