### ISSUE TITLE
Determine appropriate replacement for input method swipe pager indicator

### ISSUE THREAD

**Issue by adamwolf** [beeminder/beedroid-issues#69]
The swipe pager indicator we used doesn't work anymore.

I will be trying this: https://github.com/tommybuonomo/dotsindicator

**Comment by dreeves** [comment]
Reminder that even with that pager indicator this was invisible to everyone. Even power users were oblivious that other input methods were available. It's hard to imagine that being true once you're used to it but it seems empirically true.

So any crazy idea you may have for making it more discoverable, let's try it!

**Comment by adamwolf** [comment]
I imported a sightly different version that has a little bit of a different hint that it's swipeable.  It will be in the next preview release.

**Comment by adamwolf** [comment]
@dreeves do we need to add the toast that is missing?  I am OK not replacing it or replacing it, just lmk.  If you like it like it is, feel free to zap.

**Comment by dreeves** [comment]
(Side note: I was all excited about the lumpy swipey indicators but should now add, for epistemic hygiene, that that was before I looked at the old version again and realized that it also had a graphical swipey indicator, just not lumpy. I suppose I have no reason to think one will be better than the other, except the old one was, empirically, invisible to everyone so the lumpy version can only be an improvement!)

Let's say the toast is worthwhile if it's straightforward to add it back. Or if you see some other way to label the input screens. 

Toast strings:

1. Direct datapoint entry
2. Tally counter entry
3. Timer entry

[Insert philosophical tangent about the Pareto Dominance Principle which really wants to be a blog post or something because I'm convinced it's important even though I totally get how it seems super wrong-headed. Short version: Never accept even tiny degradations for any users. The extreme of this is https://xkcd.com/1172/ but the principled exception is that you _can_ violate Pareto dominance as long as you write a blog post about it. Like https://blog.beeminder.com/deathtofreebees/ or https://blog.beeminder.com/deathtoexp/]

**Comment by adamwolf** [comment]
My thought was that lumpy is non symmetrical, and I suspect fewer folks
will miss it because of that.

I'm fine adding the toasts back in.  I was thinking of them as announcing
you changed the input, and I thought that was pretty silly, but you bring
up a good point that they're also labels that show up at the right time and
then hide themselves.

**Comment by adamwolf** [comment]
Toasts re-added in develop, will be in 2.10.9.
